version: '3'
services:
  core:
    container_name: core
    image: allyson/core
    build:
      context: ../
      dockerfile: ./env/app/Dockerfile
    ports:
      - "8080:8080"
      - "4848:4848"
    depends_on:
      - banco
    links:
      - "banco:host-banco"
  banco:
    container_name: banco
    image: allyson/banco
    build: ./database
    ports:
      - "5433:5432"